---
- hosts: 172.31.9.176
  become: yes
  tasks:
  - name: execute linux command
    command: hostname -f
    register: myresult

  - name: display result
    debug:
       msg: "{{myresult}}"
       
     


   
