---
- hosts: mywebservers
  become: yes
  tasks:
   - name: install java 8 on ubuntu 16
     apt:
       name: "{{myjavapackonubuntu}}"
       state: present
       register: myresult
     when: ansible_os_family =="Debian"  

   - name: display the result of java 8 installation on ubuntu
     debug:
        msg: "{{myresult}}"

   - name: install java 9 on Redhat
     yum:
      name: "{{myjavapackonredhat}}" 
      state: present
      register: myresult1
     when: ansible_os_family =="RedHat"  

   - name: result of java9 installation on Redhat   
     debug:
        msg: "{{myresult1}}"



