---
- hosts: mywebservers
  become: yes
  tasks:
   - name: install java 8 on ubuntu 16
     apt:
       name: "{{myjavapackonubuntu}}"
       state: present
     when: ansible_os_family =="Debian"  

   - name: install java 9 on Redhat
     yum:
      name: "{{myjavapackonredhat}}" 
      state: present
     when: ansible_os_family =="RedHat"  

  


