---
- name: Download the tar file from the tomcat website
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.5/bin/apache-tomcat-8.5.5.tar.gz
    dest: /home/ubuntu/apache-tomcat-8.5.5.tar.gz
    force_basic_auth: yes

- name: create the directory, to install tomcat
  file:
    path: /opt/tomcat
    state: directory

- name: extract tar file
  command:
        cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-8.5.5.tar.gz -C /opt/tomcat --strip-components=1 
        creates: /opt/tomcat/LICENSE